version: "3.9"

services:
  app:
    image: helselga/hw26:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 8080:80
    volumes:
      - ./volumes:/code/volumes
    environment:
      FLASK_APP: "app.py"
      FLASK_ENV: 'production'