version: "3.9"

services:
  app:
    image: helselga/hw26:version-1
    ports:
      - 8080:80
    volumes:
      - ./volumes:/code/volumes
    environment:
      FLASK_APP: "run.py"
      FLASK_ENV: 'production'
